FROM localhost/b4-sync:latest

WORKDIR /

ENV UV_SYSTEM_PYTHON=1 \
    UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1

RUN uv sync --frozen --verbose
RUN chmod +x ./install_torch.sh
RUN ./install_torch.sh

RUN . .venv/bin/activate && python down.py
# RUN uv run python down.py

ENV OMP_NUM_THREADS=4

EXPOSE 5000

VOLUME ["/cache"]

ENTRYPOINT ["uv", "run", "convert.py"]
